apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kalavaijobs.kalavai.net
spec:
  group: kalavai.net
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      key: {type: string}
                      value: {type: string}
  scope: Namespaced
  names:
    plural: kalavaijobs
    singular: kalavaijob
    kind: KalavaiJobM
    shortNames:
    - kvs